index: 
    path: /
    controller: App\Controller\HomeController::index
quick_game:
    path: /quickgame
    controller: App\Controller\GameController::index
new:
    path: /new
    controller: App\Controller\GameController::new
records:
    path: /records
    controller: App\Controller\RecordController::index
new_record:
    path: /record/new
    controller: App\Controller\RecordController::new